### PR TITLE
improve consistency of double axes plot

### PR DESCRIPTION
**Pull request by andportnoy**
improved consistency for the double axes plot:

- added currency formatter
- actions for individual axes are grouped together
- semicolon removed on line 671

### CODE REVIEW

**Comment by andportnoy** [comment]
@chris1610 Hey Chris, great tutorial! Just wondering, what seemed wrong to you about the PR?

**Comment by chris1610** [comment]
Nothing. I manually merged your changes. Due to the nature of notebooks I wasn't sure if I could just accept your merge or if I needed to re-run on my local machine.. My intent was for my notebook to now look like your merge request. I apologize if I messed this up. I'm not a github expert :(

**Comment by andportnoy** [comment]
@chris1610 Got it! I tried to exclude all changes unrelated to content, but wasn't completely sure about it either 👍 
Could you write more about using pandas/seaborn + matplotlib for tweaking if you have time? This tutorial was incredibly helpful.

**Comment by chris1610** [comment]
Sure. Thanks for the suggestion. Are there any particular kinds of tweaks or just more general matplotlib modifications of seaborn plots?

**Pull request closed without merging**
